### ISSUE TITLE
How to use this repo as gaze inference?

### ISSUE THREAD

**Issue by WuZhuoran** [samtuhka/gazesim_tools#1]
Thanks

**Comment by samtuhka** [comment]
Oh, are you looking for something to estimate gaze directly from video feed or...? This isn't for that. This repo was used for the processing and analysis of a very specific dataset (that combined gaze data from pupil labs' hardware and software and driving simulator data from https://github.com/samtuhka/webtrajsim) and probably isn't terribly useful outside of that.
